import{a as P,S as E,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",R="54277824-efa85ad242bfacaecdcb3057f",B=15,m=async(r,t)=>(await P.get(q,{params:{key:R,q:r,page:t,per_page:B,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data,h=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".btn.load-more"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250}),M=()=>{h.innerHTML=""},g=r=>{const t=r.map(({webformatURL:i,largeImageURL:c,tags:e,likes:o,views:a,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img class="gallery-image" src="${i}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()},f=()=>{p.classList.remove("hidden")},b=()=>{p.classList.add("hidden")},A=()=>{y.classList.remove("hidden")},L=()=>{y.classList.add("hidden")};let l="",s=1;const w=15;let d=0;const u=document.querySelector(".form"),O=document.querySelector(".btn.load-more");u.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!!l){s=1,d="",M(),L(),f();try{const t=await m(l,s);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight"});return}d=t.totalHits,g(t.hits),s*w<d?A():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b(),u.reset()}}});O.addEventListener("click",async()=>{s+=1,f();try{const r=await m(l,s);g(r.hits),_(),s*w>=d&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});function _(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
